# Generated by Django 4.0.5 on 2022-06-07 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='title',
        ),
        migrations.RemoveField(
            model_name='product',
            name='title',
        ),
        migrations.CreateModel(
            name='ProductTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=200)),
                ('language', models.CharField(choices=[('en', 'En'), ('ru', 'Ru')], max_length=2)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='food.product')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=200)),
                ('language', models.CharField(choices=[('en', 'En'), ('ru', 'Ru')], max_length=2)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='food.category')),
            ],
        ),
    ]
