# Generated by Django 4.0.5 on 2022-06-18 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_remove_category_title_remove_product_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorytranslation',
            old_name='product',
            new_name='category',
        ),
    ]
