# Generated by Django 4.0.5 on 2022-06-18 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_rename_product_categorytranslation_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorytranslation',
            old_name='language',
            new_name='lang',
        ),
        migrations.RenameField(
            model_name='producttranslation',
            old_name='language',
            new_name='lang',
        ),
    ]
