# Generated by Django 4.0.5 on 2022-12-06 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_dish_alter_categorytranslation_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='products',
        ),
        migrations.CreateModel(
            name='DishProductConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grams', models.IntegerField()),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.dish')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.product')),
            ],
        ),
    ]
