# Generated by Django 4.0.5 on 2022-12-06 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_remove_dish_products_dishproductconnection'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DishProductConnection',
            new_name='DishProduct',
        ),
    ]
