# Generated by Django 4.0.5 on 2022-12-06 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_rename_dishproductconnection_dishproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='products',
            field=models.ManyToManyField(through='food.DishProduct', to='food.product'),
        ),
    ]
