# Generated by Django 4.0.5 on 2022-12-06 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0011_alter_dish_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, through='food.DishProduct', to='food.product'),
        ),
    ]
