# Generated by Django 4.0.5 on 2022-12-06 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0012_alter_dish_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishproduct',
            name='dish',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='food.dish'),
        ),
    ]
