# Generated by Django 4.0.5 on 2022-12-07 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0016_alter_dish_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='products',
        ),
        migrations.AddField(
            model_name='dish',
            name='dish_products',
            field=models.ManyToManyField(blank=True, related_name='dish_product', through='food.DishProduct', to='food.product'),
        ),
    ]
