# Generated by Django 4.0.5 on 2022-12-07 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0018_remove_dish_dish_products_dish_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, through='food.DishProduct', to='food.product'),
        ),
    ]
