# Generated by Django 4.0.5 on 2022-12-17 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0020_remove_dish_products_dish_dish_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='dish_products',
            new_name='dish_product_relations',
        ),
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(upload_to='static/dish_images'),
        ),
        migrations.AlterField(
            model_name='dishproduct',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.dish'),
        ),
    ]
