# Generated by Django 4.0.5 on 2022-12-18 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0021_rename_dish_products_dish_dish_product_relations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
