# Generated by Django 4.0.5 on 2022-12-18 15:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0023_alter_dish_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.ImageField(upload_to='menus'),
        ),
    ]
