# Generated by Django 4.0.5 on 2022-12-19 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0024_dish_creation_date_alter_menu_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='description',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
