# Generated by Django 4.0.5 on 2022-12-19 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0026_alter_dish_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
