# Generated by Django 4.0.5 on 2022-12-20 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0027_alter_dish_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='description',
            field=models.TextField(default='', max_length=300),
        ),
    ]
