# Generated by Django 4.0.5 on 2022-12-20 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0028_alter_dish_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='description',
            new_name='description_short',
        ),
        migrations.AddField(
            model_name='dish',
            name='description_full',
            field=models.TextField(default='', max_length=2000),
        ),
    ]
