name: Easy Diet Deploy

on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]

jobs:
  build:

    runs-on: ubuntu-latest
    environment: master
    
    steps:
    - uses: actions/checkout@v3
    - name: Deploy to Staging server
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: "b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcnNhAAAAAwEAAQAAAgEAtfwFZz6rr3RhfHhdkhzC3SaNpbf6Ph5y4KPrQO7NgbnZy/Lx0s9Evy2pjRELmeLGXCW62GZDzs5qwmroKUTgmZLCB6BBzXGMsxkU+xORXaPOERawPTz13/4JbWfuuC3Zi5jDb+9KX0JoaC9SnFohUbD05lN+TSerUKRyWinxlcCWeLsux6+AKIjuJgKo1Hf4zsEju8BJaEbvnfG5LwRh6nCRzosxjGtDYUMk9N+h3z0WLDGUAmIYeoBpC1lXPBYMMo8pBg5eWBMu16o2As04jxE8xd0PZr5HdacR3U/aXB0EjQeGHyvhyFx/llBEoy5WxkVfnmZ1RyGafazzx2S/FiKs4SfpnGPDT78oegIUAtZQC7b97ULIgUTovjbvj1DS9KLbeuTTUNYEqxJ/NhR5uf6yR45S9PrW31dfAU6gFmyYLdi1ocVQp+dPJOrVO6GOgdRUpIdZVgH73s18MeBaR/gP77wEAses9Qz2dQOlcTDF5kijPFJp4JfqHv5Y5NqHzW23H7lbXb1bCemYh9B8762pQvbcNcRM3mJPdGlhDaX9Frh7h/rTun9MOsEhnMOc+laqxgKpPrb/4oG34hGVmDykb3lYemvzM+fUDFJNoF9bCxvm0aHsaO2zqJfVje+OHZBFatSExNs5UcIoizx85h22v9yHxMA0S5oLL5ZBuskAAAdICslHGgrJRxoAAAAHc3NoLXJzYQAAAgEAtfwFZz6rr3RhfHhdkhzC3SaNpbf6Ph5y4KPrQO7NgbnZy/Lx0s9Evy2pjRELmeLGXCW62GZDzs5qwmroKUTgmZLCB6BBzXGMsxkU+xORXaPOERawPTz13/4JbWfuuC3Zi5jDb+9KX0JoaC9SnFohUbD05lN+TSerUKRyWinxlcCWeLsux6+AKIjuJgKo1Hf4zsEju8BJaEbvnfG5LwRh6nCRzosxjGtDYUMk9N+h3z0WLDGUAmIYeoBpC1lXPBYMMo8pBg5eWBMu16o2As04jxE8xd0PZr5HdacR3U/aXB0EjQeGHyvhyFx/llBEoy5WxkVfnmZ1RyGafazzx2S/FiKs4SfpnGPDT78oegIUAtZQC7b97ULIgUTovjbvj1DS9KLbeuTTUNYEqxJ/NhR5uf6yR45S9PrW31dfAU6gFmyYLdi1ocVQp+dPJOrVO6GOgdRUpIdZVgH73s18MeBaR/gP77wEAses9Qz2dQOlcTDF5kijPFJp4JfqHv5Y5NqHzW23H7lbXb1bCemYh9B8762pQvbcNcRM3mJPdGlhDaX9Frh7h/rTun9MOsEhnMOc+laqxgKpPrb/4oG34hGVmDykb3lYemvzM+fUDFJNoF9bCxvm0aHsaO2zqJfVje+OHZBFatSExNs5UcIoizx85h22v9yHxMA0S5oLL5ZBuskAAAADAQABAAACAD45FX/fpcQv/sUYQqYav2XuMLBg32ct8gltApsJC6s3aIibYKO7yr2zVy2sjlLnfvsyy1gCX1zupwIim47Axiq8SytgWB9um7UA9nOClUl3IJYnM8s8dLVJnt+RkcXXp3JboTc8kilQA3Lb+1sKViogXxwBoEWxMpo4IAFEJh4V410UY0JTd3Zkm0jTz/YVrzTCRP2FGZRV7MgMRk0VKoWGR9RfM2nXowo2cwRnEmnJ8TLbIMhP0h7QmRoQSgt5XmJLILO5ZfinVnTW9fCvSo9gTW85znJKzRQlM66AByFHqq6ty+YMkv524gj7GPzSc0kHn1IBpkfT7YbbA99BSzQqKYtCC7sw0b3QUtWAKWUpB4PEmh1MjdyE7VD6iNEOXmITPBLoRfhD1HwMjrzGfsSgi+lmahzAsDNnA5KVzG7w3bl6kqUXZGEu+n9wNfyZ4VVgm4bjb3y3XeCSbBQLCXAyt7cGqaMlouXn3GSE6RS1imB9J7+LfUnz3PHfJmidPGuL/YrwBd4XDjQaRBQvWCPbikWuh/xm9l2Vxvb6ixR7WdqwnIkRTE+k8rFXVM9OI5HsrbFPkg8SK57HlipUsEII8T+HyvleUnamb3h/RpRR3OSiRIBkmldAZBgfzHFrfo8vGKII9qdfCGo2LP5ldLkbi/xwcorTmWDhaC6391QBAAABADNA4EIJqoJ3+eF+g+odAOy/CEU0YZSKrpRWV/a2v1BU2UjojPdTYqNhkhaDWJFxH7wnZNxMM8bj6Cmz4j9TwvSP2JVuU0oW5OY4oWO7TpWzhKfjDsiUshen36rFTx5FK6jxGR8rKrIf/XrM/OaqvC4xhfVSkgC+9nKjs+jQgu2qWt67bIf2WVELhPIcs66b7v8FWQ/Fh6BG5bCn/PGAcbPvrrAlnxXm1MHDki41sNtE/ikw+DzVLhif2DH3su8FJxSVybcqGk3FPOqLK6mB7i2xiWtB2ntRVAoy3GE5cW5zEnuUyen2p7NqmXN8xF4w0ohO5Zm7zfZOpWg23l9pvT0AAAEBAOvG182xdEJZ58hyJFdOpPL85ncTe445lhTE79b0PfEE0kqEdGeqBbNV8hZ4rpCHPNsD6SiR/IZj+20Qz7WFH9pdH71uDS+fKnnlIhiSm2nnqW3chgySAbYz5n0qltq8ITQkv5NEfHy5DLLROwysYIe41PI0tMt+pddecNYO09zxKxsoJgqwX7m4dPsEhy1lGjBsVXpkzEz31wta1wvpsH0ofiEqfqD0ef64ymVU8zWc1cpylZPosR5Mpv29Mq9fjpSwj7GKHaHz85m33WRcKb2Y78Uu17Qdg7ybykKBlhwNYoH/89cIaB0xLwFn6ossY85/sZpmhAsC7vva9TZHpVkAAAEBAMWYA42v01rAhaTQaEcSFBqQ39VH66SHI0X2aANgiyVRdwz1nlbbPDemOWJEBgn8DLrva5+ROcVedlcrcezV0E6iwz/5Qgfr4qfdjbZSkK59c5GBoUduw8/o9vB7kuXXPKchRkunYBj7RS3KySrSYtdOzc0nAQvvpU5/AIy68WrXJpFVxhJHwgCR6WBdLsC/U3tuc0fZWtrUqCYwhB9iiWm9li/GGHTFveIRlbdmORqgRIiRaiJ9TR0xh+LKrimy5i5EY3hau7wPpUmPz7WP/ohWGA7eVQm+fcqxCsx0w+n8iqSHQceN6A5fCgAwt+EUNEEU9xWht9Fi2OJy8hQ7YvEAAAATMHNob3dtYW4wQGdtYWlsLmNvbQ=="
        ARGS: "-rlgoDzvc -i"
        SOURCE: "/"
        REMOTE_HOST: "213.171.6.213"
        REMOTE_USER: "root"
        TARGET: "/var/www/easy_diet_test"
        EXCLUDE: "/frontend/"
        SCRIPT_BEFORE: |
          whoami
          ls -al
        SCRIPT_AFTER: |
          whoami
          ls -al
          echo $RSYNC_STDOUT
