name: Easy Diet Deploy

on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]

jobs:
  build:

    runs-on: ubuntu-latest
    environment: master
    
    steps:
    - uses: actions/checkout@v3
    - name: Deploy to Staging server
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: "MIIJKAIBAAKCAgEA5ukKrlFo0FxHoccFZISOGhe2JicRfeZROuhLuRcYXD7PxlOKAMxuv7p2+n9knyysDZTE/ld6dHo1QLLulRTkzcTyE10MFv4jJHz7fBRYJ6I79mYsEZsP4epTt8PuMuE0rNitJuU4iijUkZNNTALSZe/XNoypS7J5zBLUUQZ1FAg0pdISq2ZAP+iei4T52ZHuoWb7KfncQjZ+ZyhHHPhMsJ+FMbVVAinjWgqL/qo3pha68oXl+kEBHDT1AjkS+1z84QcTW3FqET8SAe0d4uAu3xB2O2rneUTaibc78d5jTLgo9VjPB803VvUIZrVXICjLmEtuSfN4uvcjz8EYjyo0MW3WpEP/BxBogFBeJ1bYm00gbVpisn3vqnVc6bvWPmdjoT0yGABuNncie8ysBC8URIK5JqYLl4A/hBl622SjJTUSwGhkUX9xjLvJhDRLOxLU2nEui6vRHkZ0GthDUsSGqBqOSqGRl+aVEuBGzvDY4gphllMwIdv7cahoMKygpofmACsCY472W7ys5bwtArfO8fovfxELk9VTdvkiGc9aWVKBZ31nuRBs67m7YtA3kzyQgrXM+r+3UHkAUkSrZF4qhDJaf+ttHRAdISf89yfC6bLx59wFZOlq0QOVJzVRuFUSyrZimV8GvY+plaZdEy3PLxbjG1AhWRJBBrjdHiPAhnMCAwEAAQKCAgAI8fneyJA/E3bCRCOn12C/5FpDPnE1h4tvCkULXbiCXlE4lXo7pK/HpVFq9oNvN9D50mESmftIRtxdmMZC/TpjOaAdHZYpz9zhqCZ/5zPbuTO0dxR5oXWrN/jX83L8rUUX9b7jdQQh319jZ6maFQ6R3LQ2zJqEWwd6ieIyugV6v1n2xd1rnrxEyDNYI/sf3BY6p3LPF1Baj6I0RyxWFCJjFz2W2uJOVqa+5rix/BBy0opEeekaWZP8Q+rtPp5xzBI5z3HcXCzn5SHCnwJw4blpx8lPbPPxpTgIF2fu60Fn3Ucs61dTLeEucQigc0xK6879+TIZEvcC2y8bzcGwo3RpFkgryzgbvUCCJ/seZSDaGnsBkoY8Sp51FW5iRL0xr62SXRAMu6TmTM7lAspqmQNk048RMl0ViV3TnUjFzuZxQILD0hCB7sHpzVTBgL3x6L38dI73hudb312LsR8akvB3kNskqgYtdr5BWRolsDpFx9IDsCaeojUaavZFiNIr9N0g8IqhypbS/4yxk6Ofuv5czWUaKHvY+FHdPfa6GWnpyU5+cka++2iZfiDmLHUPgl/ZwEIUb57D1bBbNLEKMgczTFOYA6nWD2wMRYdC8Pg40ui8rAbVia6OSsIVpiJenB5NBRzTZDcihqzgHYSxI+eLVbosiksnMYCMY6wvJTaL8QKCAQEA+dTqeiVPO3gJmtPNb6exMAjIyFdrjnolncYBZH82I2fCTBw63c0qri+/Zh7wVFrC38/8lZXAnru013zXDOiInQ2pRTsg9zkZmKRD2mSmg8rfIgZJ+FCKSGPUntn6MfSy10BtbeB9n07fD7FrM/AB8Evm8ip8aOMtW73lpHcj7OiPcFLZAmK/tGrKLHnodi2aGCuG4DCHibB6Ll70oAPEsY37ile4TzEc+YTZRhVYwwc1ax3FkishuasEeiNpgIkVYbuDEbqz32/9S0+rbgiUSJ++QkW/1dkl/GV+7gS8yLVvnPOzU8i9t9vFzvlnnLPTiv3tvALr84zfBb9+kHhT0QKCAQEA7JyIDg66KkDWYnWXiboXm0ZS0ysb06vMJI//RLkeDvyOQt7Lq+acMQXHNGkTCbsV4i2Jk95lruj/h3YVcz+DEiC4EX+r7QTziott8e358erA9KIbBxaOpHbZnAfaivhJdcixvhXR55PnArtkNEz8U3I3SULw+YQP7TT9f4uX6U/5y6b0HdUtHHBx4AKfg1j/tiD8yXM6Qj4DWMXchSEvjepa0GgfU1EPVCFU6zrRg26itCgfEz5LCTEDrGyhvRr9Fq2Byl5TnopiIs2u7C296o75TumeZyrjNhHJS9ppMHsFSCJ/9mI911wxgnCG/PJcgrftWcz4gcPpssFg/BibAwKCAQAH6fKzg9MKsza6rNLpIoq+Vsjlb798d+oRIWCR6mWwoWzKNGq48/LSKbkKZxh905IwvMnngyLi5FdKLC4zvnn1X6VpCAJ3Ulu5NhrgJCgSLK78yO4263Y17NOjZIxEYNf5cZUF0gKotTrjqF8Y+hVVo1Hhge8G84tQSKepmgyNSKCikj1FkhM4h9l3pzTx6WfkNBzFpUPl3K1CIsfk+bmVVkYNj9HK0Gd2j/rB+ZMiOmw6xGqpwqwC0aQGqnCBHdaLjgEM4rkn7sg7Rn7LsYHg+w5v0v3MrGBDqoNmzsecJAMxGZcopEc+N7wAXm4lzJx63qhVOFJ5GJFIAVTlBqrBAoIBADTmGhTqffyMWmHQ4HxOOpDgfAvyC1qbghx6hRucN3gqRrP0k5xvBmR/YjX5d+QpC49xltyUUC92sApdABawEGGxJvXikVGAVeKXoZEBH2xSi6klxN0k0ec7GxOjPdzr/aBzqilRP4iCrJcTxidbPt55HpsmeDGQsO7bdgFZ+DCVTMeXH+S7kEZXbV4jt/3pm+HgJiPzuwasTps+QTsSXEtiJcOKQ9agvMiWWyHsGINF7OJSRgBLYQNBDg0yjEZ3DjZPvEC+Lfu3/JDDY2QyJc+W/24BFQUDtaCVAWgQAIxyNJAYBnvTIvhPCFKdTdCnbr9a15nIFZcNceYhDcnOxnkCggEBAIo558/6EaIGMRkI03t1gKyY9Q7ZdMq21eQGrGMqcDujnuAMyhCUssjp7iJes+SHny2DHk7AenYkeCEZB9NWeuF4Dmc0IyhhLlsQGQFXSLGp2KZVIL6K3l6VRC/PQvw+Zu8pqffx1uumoKVT9Gv89qB57ZqNU2CyUgFRkVYXuK/tF4v42rsk+MGq8UqawNLec9XnhRyVe1eemzLxgqMbEP67pF2dXG8KjvNaG4BTubL9dL4DpUXZD3V4uuuoxozxTketkTECgIIEdWWWLdlI68dzBDdMPD6cD0SsezOHgh16rye0ithVd7WDcevfw+cJcUG8f39CEVJ2Wbu1kEEvfts="
        ARGS: "-rlgoDzvc -i"
        SOURCE: "/"
        REMOTE_HOST: "213.171.6.213"
        REMOTE_USER: "root"
        TARGET: "/var/www/easy_diet_test"
        EXCLUDE: "/frontend/"
        SCRIPT_BEFORE: |
          whoami
          ls -al
        SCRIPT_AFTER: |
          whoami
          ls -al
          echo $RSYNC_STDOUT
